### ISSUE TITLE
Fix Style.css

### ISSUE THREAD

**Issue by NinjaAung** [tekperfect/devops-docs#16]
In relation to the sidebar, color formating is terrible
![Screen Shot 2020-11-14 at 12 15 43 PM](https://user-images.githubusercontent.com/37085146/99156103-41163100-2673-11eb-869a-22f6a66d6735.png)

**Comment by 3salaz** [comment]
Already have this fixed on my branch gonna push later today @NinjaAung

**Comment by NinjaAung** [comment]
Would be nice to push it now, students are looking at it now. No worries I like the highlight stuff pretty cool!
